# Generated by Django 5.2.1 on 2025-05-24 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destinations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='', max_length=100)),
                ('state', models.CharField(default='', max_length=100)),
                ('country', models.CharField(default='', max_length=100)),
                ('postal_code', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('product_id', models.CharField(default='', max_length=100)),
                ('ref_id', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('Sku', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sla', models.CharField(default='', max_length=100)),
                ('price_delivery', models.IntegerField(default=0)),
                ('delivery_company', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default='', max_length=100)),
                ('date', models.DateField()),
                ('discount', models.IntegerField(default=0)),
                ('shipping', models.IntegerField(default=0)),
                ('products_price', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('destination_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='api.destinations')),
                ('origin_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='api.warehouses')),
            ],
        ),
        migrations.CreateModel(
            name='DetailsOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('order', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='api.orders')),
                ('product_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='api.products')),
            ],
        ),
    ]
